---
# tasks file for cc-ec2-builder
- name: wait for SSH to become available
  wait_for: port=22 delay=10 state=started
- name: copy private key used to access code commit repo over SSH
  s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_object }}"
    dest: "~/.ssh/{{ s3_object }}"
    mode: get
- name: set ssh private key mode to owner read
  file: 
    path: "~/.ssh/{{ s3_object }}"
    mode: 0400
- name: create ssh config file
  template:
    src: ssh-config
    dest: ~/.ssh/config
    mode: 0600
- name: add Code Commit server in us-east-1 (only supported region) to SSH known_hosts
  shell: ssh-keyscan git-codecommit.us-east-1.amazonaws.com >> ~/.ssh/known_hosts
- name: install git package
  sudo: yes
  yum: 
    name: git 
    state: latest
#- name: update to latest AWS CLI tools
#  shell: pip install --upgrade awscli
- name: set git global email address so we can commit and push updates
  shell: "git config --global user.email builder@localhost.local"
- name: "git clone {{ repo_name }}"
  git: 
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dest }}"