---
# tasks file for ec2-launcher
- name: create an ec2 instance
  ec2:
    region: "{{ region }}"
    image: "{{ ami }}"
    key_name: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_profile_name: "{{ instance_profile_name }}"
    instance_type: "{{ instance_type }}"
    wait: yes
    instance_tags:
      role: builder
    count: "{{ count }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: True
  register: ec2